### ISSUE TITLE
Update NuGet

### ISSUE THREAD

**Issue by bddckr** [JBildstein/SpiderEye#10]
There have been numerous improvements on master that aren't yet available on nuget.org. I'd like to see the latest state being up there!

I'm currently using master with my own built nupkgs, but would love to keep in sync with upstream :) Especially the change to set `SynchronizationContext.Current` is a great one I'm making use of to get some generic host + Rx stuff rolling. Thanks a lot for the hard work!

**Comment by ABildstein** [comment]
I intentionally didn't update because I wanted to finish a few things and make a beta.1 version. It just took a bit longer than I wanted. The most important parts are done though and I'll be able to push the new version probably tomorrow.

And thank _you_, I'm glad you find it useful :)

**Comment by ABildstein** [comment]
The new version (1.0 beta.1) is now published and the NuGet packages are available.

**Comment by bddckr** [comment]
Thanks a lot! Working great here.
