### ISSUE TITLE
Expose a Navigating event

### ISSUE THREAD

**Issue by bgavrilMS** [JBildstein/SpiderEye#17]
**Describe the feature you'd like**
The IWindow interface currently exposes events such as `Closed`, `Closing` and `Shown`, but not an event that fires whenever the browser navigates from one page to another. This `Navigating` would occur before navigation and would advertise the Url. 

```csharp
window.Navigating += (sender, args) => {
    if (args.Url.AbsoluteUri == "https://well.known.url") 
   { 
        _url = args.Url; // capture the final url for later use
         window.Close();
   }
}
```
On Windows the `WebBrowser` object exposes a [Navigating event](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser.navigating?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Forms.WebBrowser.Navigating);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=netcore-3.1). It also exposes a mechanism for cancelling the navigation, which would be very useful.  

**Reason for this feature request**
I'm looking at using a webview (cross-plat) for showing the browser in an Auth SDK (for the project https://github.com/AzureAD/microsoft-authentication-library-for-dotnet)

The way authentication works is that the user navigates to an authorization URL (for example [this one](https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?scope=offline_access+openid+profile+user.read&response_type=code&client_id=1d18b3b0-251b-4714-a02a-9956cec86c2d&redirect_uri=http%3A%2F%2Flocalhost&client-request-id=fca0fec6-8cc9-4f96-a5f6-e2d61a7ce47c&x-client-SKU=MSAL.NetCore&x-client-Ver=4.14.0.0&x-client-OS=Microsoft+Windows+10.0.18363&prompt=select_account&code_challenge=qodkCBrBuAxYD85qovsqOamK2u5_IS5zC_cJ9GizmpI&code_challenge_method=S256&state=cf6e15fc-809e-416e-80fc-34444dcb9cd0a59f5c8e-3db5-4e27-829c-67b7743488e9)) then the server asks the user to authenticate (or reset password or whatever). Several redirects occur. Finally the server redirects the browser to a well-known uri. At this stage, the library that started the browser needs to detect that this final uri has been reached and return the full URL back to the identity SDK, as it contains a GET param with a code that can  later be exchanged for a security token.

**Comment by ABildstein** [comment]
sorry that took a while but it's implemented now.

The Window class now as a `Navigating` event that contains the URL it will navigate to and by setting `Cancel` to true you can stop the request.
The event is fired for each redirect except when using IE, there only the initial URL is sent.

The `PageLoaded` event now also contains the loaded URL.
