### ISSUE TITLE
Hide controlBox and border feature

### ISSUE THREAD

**Issue by nguyenvanbien95** [JBildstein/SpiderEye#18]
**Describe the feature you'd like**
A clear and concise description of the feature you'd like to have.
I want to remove border and control box.

**Reason for this feature request**
A clear and concise description of the reason(s) for this feature request.
In some case, application is developed for Rasberry Pi. Pi has a touch monitor, and my user don't be closed program.

**Comment by ABildstein** [comment]
I'll look into it. I think all OS support it but I need to check the specific APIs.

Do you actually need windows without borders or do you need fullscreen windows?

**Comment by nguyenvanbien95** [comment]
Yeah, I actually need fullscreen windows.

**Comment by bddckr** [comment]
If those APIs allow to toggle this behavior, that would be great, too! I can see the need to do a regular fullscreen view for video playing and the likes.

**Comment by nguyenvanbien95** [comment]
> If those APIs allow to toggle this behavior, that would be great, too! I can see the need to do a regular fullscreen view for video playing and the likes.
Hey @bddckr 
Do you play video of youtube on webview on linux? My video have no sound. Can you help me?

**Comment by ABildstein** [comment]
sounds good! I wanted to improve the minimize/maximize behavior of windows for a while so that fits well into that.

**Comment by bddckr** [comment]
@nguyenvanbien95 No I do not, and a separate issue is most likely better for that to get someone who can help 🤞

**Comment by nguyenvanbien95** [comment]
@bddckr I had done that. Thank you.

**Comment by ABildstein** [comment]
It's implemented now. The `Window` class now contains:

 - the `BorderStyle` property to get borderless windows
 - `EnterFullscreen` and `ExitFullscreen` methods
 - `Maximize` and `Unmaximize` methods
 - `Minimize` and `Unminimize` methods

and the `SetWindowState` method has been removed.

This now matches how many OS native methods are implemented and allows more fine grained control over the sizing behavior.
