### ISSUE TITLE
Module not found: ./spidereye-bridge

### ISSUE THREAD

**Issue by jonpc2020** [JBildstein/SpiderEye#25]
Running the command ng server, reports the following error

Error: E:/Projects/Net/Samples/Net.Core/SpiderEye2/SpiderEye-master/Source/SpiderEye.Client/src/index.ts
Module not found: Error: Can't resolve './spidereye-bridge' in 'E:\Projects\Net\Samples\Net.Core\SpiderEye2\SpiderEye-master\Source\SpiderEye.Client\src'

1. Open a command prompt
2. Run the ng serve command

the Angular project should build ok

 - OS: Windows 10

**Comment by ABildstein** [comment]
Thank you for the bug report, it should be fixed now!
