### ISSUE TITLE
Can I use Chrome Extension or Edge (Chrome) Add-ons in SpiderEye

### ISSUE THREAD

**Issue by zydjohnHotmail** [JBildstein/SpiderEye#27]
Hello:
I want to know if I can use Chrome Extension or Microsoft Edge (Chrome) Add-ons in SpiderEye.
I am interested in only one of such Edge Add-ons, it is called Privacy Pass extension, it can be downloaded from Google web store at: 
https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi 
I have tested on Edge (Chrome) browser (Version 88.0.705.63 (Official build) (64-bit) on Windows 10 (Version 20H2), it works.
You can do some testing with this web site: https://buff.bet/
But you have to manually solve an easy Captcha challenge, then you will get 5 “tokens” or credits, then next time, you visit the same page, you don’t have to solve a Captcha challenge, until all the 5 “tokens” or credits run out, each time, it will cost one “token” or credit, which can last about 2 hours.
I have tried to install Privacy Pass extension with WebView2 (nuget version 1.0.705.50) in my C# project (WinForm .Net 5 App), but it failed to work, as hCaptcha consider WebView2 with such extension is a bot, not a human being.  But I can use it will WebView2 without Privacy Pass extension, but only for 2 hours, after 2 hours, I have to manually solve the Captcha challenge again.
Let me know if SpiderEye can be used with Privacy Pass extension, which can use for about 10 to 12 hours without having to manually solve Captcha challenges.
If yes, please provide some instructions. My IDE is: Visual Studio 2019 Version 16.8.4.
Thanks,

**Comment by ABildstein** [comment]
As your tests show it may (somewhat) work with WebView2 but this project includes various different webviews. The fact that WebView2 can be used is only an implementation detail and so it is not accessible to users/developers.

You'll be better off to directly use the WebView2 control that Microsoft provides and use the available APIs there. The folks at Microsoft will be able to help you better: [MicrosoftEdge/WebView2Feedback](https://github.com/MicrosoftEdge/WebView2Feedback/issues)
