### ISSUE TITLE
Can we get access to NativeWindow?

### ISSUE THREAD

**Issue by vpopescu** [JBildstein/SpiderEye#36]
**Describe the feature you'd like**
I'd like the NativeWindow to be made accessible. Currently it's defined as:

```
internal IWindow NativeWindow { get; }
```

I want to be able to set a parent for the window, and also to change its visibility on demand.

**Reason for this feature request**
I am integrating with a library where the SpiderEye window is not the primary library. I need to be able to control two things:

1. Set the SpiderEye.Window's parent to be my application's main window
2. Run the window either as a visible or hidden window

For the first item, today I don't yet have a way.
For the second item, the best I can do today is play with the height/width, but there is still portions of the titlebar left when size is 0x0.

**Comment by clibequilibrium** [comment]
@vpopescu  just use Reflection. Properties with { get; } get converted to backing fields.

```Csharp
  private static FieldInfo GetBackingField(PropertyInfo pi)
        {
            if (!pi.CanRead || !pi.GetGetMethod(nonPublic: true)!.IsDefined(typeof(CompilerGeneratedAttribute), inherit: true))
                return null!;
            var backingField = pi.DeclaringType!.GetField($"<{pi.Name}>k__BackingField", BindingFlags.Instance | BindingFlags.NonPublic);
            if (backingField == null)
                return null!;
            if (!backingField.IsDefined(typeof(CompilerGeneratedAttribute), inherit: true))
                return null!;

            return backingField;
        }
   ```

```CSharp
var property = typeof(Window).GetProperty("NativeWindow", BindingFlags.Public | BindingFlags.NonPublic | 
 BindingFlags.Instance);

FieldInfo field= GetBackingField(typesProperty);
var value = field.GetValue(window)! as IWindow; // you can make your own IWindow that replicates the internal one, or just keep it as object...
 ```

**Comment by vpopescu** [comment]
Using reflection to access a field which was purposefully reserved as internal seems wrong.

**Comment by clibequilibrium** [comment]
> Using reflection to access a field which was purposefully reserved as internal seems wrong.

You are welcome 😄 

> For the first item, today I don't yet have a way.

Is it an issue of you not having a way or you having a moral disagreement on the solution I provided ? 
Also, you have the source code of the package, so you can fork it and make the property public, that would be another way to deal with it .

Or you are also welcomed to make a PR, that's how open source works
